version: '3.8'

services:
  mlflow-server:
    build:
      context: .
      #dockerfile: Dockerfile.mlflow
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5001 > mlflow.log 2>&1 &
    ports:
      - "5001:5001"
    volumes:
      - .:/mlflow/mlruns
    networks:
      - mlflow-network

networks:
  mlflow-network:
    driver: bridge
