model:
  max_recommendation: 250
data_loader:
  song_data_file: "music/song_data.csv"
  train_file: "music/10000.txt"
train_infer:
  state_matrix_file: "music/state_matrix.csv"
  small_set_file: "music/small_set.csv"
